### ISSUE TITLE
Event does not exist when displaying tasks for some persons

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#151]
Merged a bunch of stuff last night, pushed to master, noticed a bug this morning:

1. Run amy.
2. Go to 'all persons'  http://127.0.0.1:8000/workshops/persons
3. Pick person F1 (all is good).
4. Pick person F10: crash bang boom when displaying a task because "Event matching query does not exist".

I'm guessing this is a data import error - I'll dig into it this afternoon when I'm back online.

**Comment by wking** [comment]
On Sun, Jan 18, 2015 at 03:57:43AM -0800, Greg Wilson wrote:
> 4. Pick person F10: crash bang boom when displaying a task because
> "Event matching query does not exist".

Here's the traceback Django shows in the 500 result:

  Traceback:
    File "/.../django/core/handlers/base.py" in get_response
      111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/.../amy/workshops/views.py" in person_details
      181.     return render(request, 'workshops/person.html', context)
    File "/.../django/shortcuts.py" in render
      48.     return HttpResponse(loader.render_to_string(*args, **kwargs),
    File "/.../django/template/loader.py" in render_to_string
      178.         return t.render(context_instance)
    File "/.../django/template/base.py" in render
      148.             return self._render(context)
    File "/.../django/template/base.py" in _render
      142.         return self.nodelist.render(context)
    File "/.../django/template/base.py" in render
      844.                 bit = self.render_node(node, context)
    File "/.../django/template/debug.py" in render_node
      80.             return node.render(context)
    File "/.../django/template/loader_tags.py" in render
      126.         return compiled_parent._render(context)
    File "/.../django/template/base.py" in _render
      142.         return self.nodelist.render(context)
    File "/.../django/template/base.py" in render
      844.                 bit = self.render_node(node, context)
    File "/.../django/template/debug.py" in render_node
      80.             return node.render(context)
    File "/.../django/template/loader_tags.py" in render
      65.                 result = block.nodelist.render(context)
    File "/.../django/template/base.py" in render
      844.                 bit = self.render_node(node, context)
    File "/.../django/template/debug.py" in render_node
      80.             return node.render(context)
    File "/.../django/template/defaulttags.py" in render
      312.                 return nodelist.render(context)
    File "/.../django/template/base.py" in render
      844.                 bit = self.render_node(node, context)
    File "/.../django/template/debug.py" in render_node
      80.             return node.render(context)
    File "/.../django/template/defaulttags.py" in render
      201.                             nodelist.append(node.render(context))
    File "/.../django/template/debug.py" in render
      93.             output = force_text(output)
    File "/.../django/utils/encoding.py" in force_text
      83.                     s = six.text_type(s)
    File "/.../amy/workshops/models.py" in __str__
      282.         return '{0}/{1}={2}'.format(self.event, self.person, self.role)
    File "/.../django/db/models/fields/related.py" in __get__
      572.                 rel_obj = qs.get()
    File "/.../django/db/models/query.py" in get
      357.                 self.model._meta.object_name)
  Exception Type: DoesNotExist at /workshops/person/10
  Exception Value: Event matching query does not exist.

So Task.__str__ is crashing if the task object isn't associated with
an Event.  In a Django shell, we can see that the broken task has 7594
as the event ID:

  $ python3.4 ./manage.py shell
  >>> from workshops.models import Person
  >>> person = Person(id=10)
  >>> person.task_set.count()
  1
  >>> task = person.task_set.get()
  >>> task.role
  <Role: learner>
  >>> task.event_id
  7594
  >>> task.event
  Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/home/wking/.local/lib64/python3.4/site-packages/django/db/models/fields/related.py", line 572, in __get__
      rel_obj = qs.get()
    File "/home/wking/.local/lib64/python3.4/site-packages/django/db/models/query.py", line 357, in get
      self.model._meta.object_name)
  workshops.models.DoesNotExist: Event matching query does not exist.

But we only have 330 events in the database:

  >>> from workshops.models import Event
  >>> Event.objects.count()
  330

I'm not sure what's going wrong in the migration script, but hopefully
that gives you some extra context to find the bug :).

**Comment by gvwilson** [comment]
Fixed by #152 - `migrater.py` had a bug.
