### ISSUE TITLE
Tests fail for app workshops

### ISSUE THREAD

**Issue by narayanaditya95** [swcarpentry/amy#218]
Hi, 
Running tests on workshops app gives the same error.
```
Creating test database for alias 'default'...
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_get_future_events (workshops.test.test_event.TestEvent)
Test that the events manager can find upcoming events
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 14, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_get_ongoing_events (workshops.test.test_event.TestEvent)
Test the events manager can find all events overlapping today.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 14, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_get_past_events (workshops.test.test_event.TestEvent)
Test that the events manager can find past events
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 14, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_event_with_notes (workshops.test.test_event.TestEventNotes)
Make sure event with notes are correctly stored
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 247, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_event_without_notes (workshops.test.test_event.TestEventNotes)
Make sure event without notes don't have NULLed field ``notes``
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 247, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_add_minimal_event (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_add_two_minimal_events (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_can_request_all_events (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_events_view_paginated (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_invalid_items_per_page_gives_default_pagination (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_non_integer_page_no_returns_first_page (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_page_no_too_large_returns_last_page (workshops.test.test_event.TestEventViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_event.py", line 112, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_fixture_notes (workshops.test.test_site.TestSiteNotes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_site_created_without_notes (workshops.test.test_site.TestSiteNotes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_match_instructors_on_one_skill (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_match_instructors_on_two_skills (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_non_instructors_not_returned_by_search (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_one_instructor_by_airport (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_one_instructor_near_airport (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_one_instructor_near_latlong (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_two_instructors_by_airport (workshops.test.test_instructors.TestLocateInstructors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_instructors.py", line 9, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_event_name_dropped (workshops.test.test_util.BulkUploadUsersViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 189, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_upload_existing_user (workshops.test.test_util.BulkUploadUsersViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 189, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_upload_existing_user_existing_task (workshops.test.test_util.BulkUploadUsersViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 189, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_basic_parsing (workshops.test.test_util.UploadPersonTaskCSVTestCase)
See Person.PERSON_UPLOAD_FIELDS for field ordering
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 30, in test_basic_parsing
    person_tasks, _ = self.compute_from_string(csv)
  File "/home/aditya/amy/workshops/test/test_util.py", line 21, in compute_from_string
    csv_buf = StringIO(csv_str)
TypeError: initial_value must be unicode or None, not str

======================================================================
ERROR: test_csv_with_mislabeled_field (workshops.test.test_util.UploadPersonTaskCSVTestCase)
It pays to be strict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 49, in test_csv_with_mislabeled_field
    person_tasks, empty_fields = self.compute_from_string(bad_csv)
  File "/home/aditya/amy/workshops/test/test_util.py", line 21, in compute_from_string
    csv_buf = StringIO(csv_str)
TypeError: initial_value must be unicode or None, not str

======================================================================
ERROR: test_csv_without_required_field (workshops.test.test_util.UploadPersonTaskCSVTestCase)
All fields in Person.PERSON_UPLOAD_FIELDS must be in csv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 42, in test_csv_without_required_field
    person_tasks, empty_fields = self.compute_from_string(bad_csv)
  File "/home/aditya/amy/workshops/test/test_util.py", line 21, in compute_from_string
    csv_buf = StringIO(csv_str)
TypeError: initial_value must be unicode or None, not str

======================================================================
ERROR: test_empty_field (workshops.test.test_util.UploadPersonTaskCSVTestCase)
Ensure we don't mis-order fields given blank data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 56, in test_empty_field
    person_tasks, _ = self.compute_from_string(csv)
  File "/home/aditya/amy/workshops/test/test_util.py", line 21, in compute_from_string
    csv_buf = StringIO(csv_str)
TypeError: initial_value must be unicode or None, not str

======================================================================
ERROR: test_serializability_of_parsed (workshops.test.test_util.UploadPersonTaskCSVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 64, in test_serializability_of_parsed
    person_tasks, _ = self.compute_from_string(csv)
  File "/home/aditya/amy/workshops/test/test_util.py", line 21, in compute_from_string
    csv_buf = StringIO(csv_str)
TypeError: initial_value must be unicode or None, not str

======================================================================
ERROR: test_verify_email_caseinsensitive_matches (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_verify_event_doesnt_exist (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_verify_existing_user_has_workshop_role_provided (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_verify_name_matching_existing_user (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_verify_role_doesnt_exist (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_verify_with_good_data (workshops.test.test_util.VerifyUploadPersonTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_util.py", line 79, in setUp
    super(CSVBulkUploadTestBase, self).setUp()
  File "/home/aditya/amy/workshops/test/base.py", line 36, in setUp
    self._setUpInstructors()
  File "/home/aditya/amy/workshops/test/base.py", line 85, in _setUpInstructors
    url='http://hermione.org', username="granger.h")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_site_by_full_domain (workshops.test.test_search.TestSearchSite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_search.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_site_by_partial_name (workshops.test.test_search.TestSearchSite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_search.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_site_when_site_matching_turned_off (workshops.test.test_search.TestSearchSite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_search.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_site_with_multiple_matches (workshops.test.test_search.TestSearchSite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_search.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_search_for_site_with_no_matches (workshops.test.test_search.TestSearchSite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_search.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_task_detail_view_reachable_from_event_person_and_role_of_task (workshops.test.test_tasks.TestTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_tasks.py", line 18, in setUp
    username="person1")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_task_edit_view_reachable_from_event_person_and_role_of_task (workshops.test.test_tasks.TestTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_tasks.py", line 18, in setUp
    username="person1")
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_has_upcoming_events (workshops.test.test_landing_page.TestLandingPage)
Test that the landing page is passed some
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_landing_page.py", line 63, in setUp
    self._setUpUsersAndLogin()
  File "/home/aditya/amy/workshops/test/base.py", line 139, in _setUpUsersAndLogin
    email="sudo@example.org", password=password)
  File "/home/aditya/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/home/aditya/amy/workshops/models.py", line 154, in save
    super().save(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_display_person_correctly_with_all_fields (workshops.test.test_person.TestPerson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_person.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_display_person_correctly_with_some_fields (workshops.test.test_person.TestPerson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_person.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_edit_person_email_when_airport_not_set (workshops.test.test_person.TestPerson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_person.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_edit_person_email_when_all_fields_set (workshops.test.test_person.TestPerson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_person.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

======================================================================
ERROR: test_edit_person_empty_family_name (workshops.test.test_person.TestPerson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aditya/amy/workshops/test/test_person.py", line 10, in setUp
    super().setUp()
TypeError: super() takes at least 1 argument (0 given)

----------------------------------------------------------------------
Ran 48 tests in 0.860s

FAILED (errors=48)
Destroying test database for alias 'default'...
```

No changes have been made to the app. Running  ```Django==1.7.5``` and ```requests==2.5.3```

**Comment by r-gaia-cs** [comment]
@narayanaditya95 From your log error,

~~~
TypeError: super() takes at least 1 argument (0 given)
~~~

you are probable using Python2. `amy` is only compatible with Python3. This was one decision that our team did to avoid lots of problems due unicode. Could you try again using Python3?

~~~
$ python3.4 manage.py test
Creating test database for alias 'default'...
................................................
----------------------------------------------------------------------
Ran 48 tests in 10.906s

OK
Destroying test database for alias 'default'...
~~~

**Comment by narayanaditya95** [comment]
@r-gaia-cs Thank you. Using Python3 shows no error.
Looking forward to contributing to the project.

**Comment by r-gaia-cs** [comment]
I'm closing this based on @narayanaditya95 comment.

@narayanaditya95 can you send a pull request making clear at `README.md` that this project is only compatible with Python3?
