### ISSUE TITLE
Create superuser step fails with NOT NULL constraint failed: workshops_person.last_login

### ISSUE THREAD

**Issue by npch** [swcarpentry/amy#261]
Trying to install Amy locally using the instructions in the README. At the step to create a superuser, I get a failure - details below. Have replicated trying different superuser details in case spaces in the entry fields were the issue. I'm using the test dataset created using the previous step, no errors reported.

(py3k)MBANCH:amy nhong$ python3 manage.py createsuperuser
Username: neil
Personal: Neil
Family: Chue Hong
Email: n.chuehong@software.ac.uk
Password: 
Password (again): 
Traceback (most recent call last):
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 149, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/Users/nhong/Documents/src/npch/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/Users/nhong/Documents/src/npch/amy/workshops/models.py", line 159, in save
    super().save(*args, **kwargs)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 971, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

**Comment by wking** [comment]
On Thu, May 07, 2015 at 07:16:08AM -0700, Neil Chue Hong wrote:
> (py3k)MBANCH:amy nhong$ python3 manage.py createsuperuser
> Username: neil
> Personal: Neil
> Family: Chue Hong
> Email: n.chuehong@software.ac.uk
> Password: 
> Password (again): 
> Traceback (most recent call last):
>   File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

Hmm, I'm not able to reproduce this locally:

  $ git log -1 --oneline
  cec3868 Merge pull request #255 from gvwilson/making-human-names-readable
  $ rm db.sqlite3
  $ make migrations
  $ python3 manage.py createsuperuser
  ...
  Superuser created successfully.
  $ rm db.sqlite3
  $ make database
  $ python3 manage.py createsuperuser
  ...
  Superuser created successfully.

**Comment by npch** [comment]
As additional information, the createsuperuser command does work if I edit db.sql manually to remove the NOT NULL constraint on workshops_person.last_login and regenerate the database.

I am then able to start Amy using "make serve" and login using the superuser credentials I created.

I confirm I'm using commit cec3868.

**Comment by wking** [comment]
From your stack trace it looks like you're using Python 3.3 (I'm using
3.4).  I doubt that would be the issue though.  What version of Django
are you using?  Any chance you can reproduce your failure in a Docker
container?

**Comment by npch** [comment]
(py3k)MBANCH:amy nhong$ python -V
Python 3.3.5 :: Anaconda 2.2.0 (x86_64)
(py3k)MBANCH:amy nhong$ python -c "import django; print(django.get_version())"
1.8.1

I can try and reproduce in a Docker container, but this won't entirely resolve my issue as I'm looking to get Amy up and running under Mac OS X Yosemite. Might at least help determine if it's a recent update to one of the Amy dependencies though. About to hit the road again, so will attempt clean install into a Docker container on Monday.

**Comment by pbanaszkiewicz** [comment]
That's probably my fault. I should have specified in `requirements.txt` a Django version >=1.7, <1.8.

Currently we have a PR #243 that solves the issues.

@npch please downgrade your Django version to 1.7.* and try again.
@wking could you please review #243? Thanks.

**Comment by pbanaszkiewicz** [comment]
Hi @npch,

I've just merged #243, so the newest code in `master` branch will probably solve your problem.

Cheers

**Comment by npch** [comment]
Still getting the same issue. I wonder if it's an SQLite version issue?

(py3k)MBANCH:amy nhong$ sqlite3 --version
3.8.4.1 2014-03-11 15:27:36 018d317b1257ce68a92908b05c9c7cf1494050d0

(py3k)MBANCH:amy nhong$  git log -1 --oneline
cc5a178 Merge branch 'gvwilson-itemizing-unpublished-workshops'

(py3k)MBANCH:amy nhong$ python -c "import django; print(django.get_version())"
1.8.1

(py3k)MBANCH:amy nhong$ make test
python3 manage.py test
Creating test database for alias 'default'...
/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/crispy_forms/utils.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  default_field_template = memoize(default_field_template, {}, 1)

/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/crispy_forms/templatetags/crispy_forms_filters.py:20: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  uni_formset_template = memoize(uni_formset_template, {}, 1)

/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/crispy_forms/templatetags/crispy_forms_filters.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  uni_form_template = memoize(uni_form_template, {}, 1)

/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:197: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  whole_uni_formset_template = memoize(whole_uni_formset_template, {}, 1)

/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:202: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  whole_uni_form_template = memoize(whole_uni_form_template, {}, 1)

...................................................
----------------------------------------------------------------------
Ran 51 tests in 14.811s

OK

(py3k)MBANCH:amy nhong$ python3 manage.py createsuperuser
...
Traceback (most recent call last):
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 149, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/Users/nhong/Documents/src/npch/amy/workshops/models.py", line 83, in create_superuser
    user.save(using=self._db)
  File "/Users/nhong/Documents/src/npch/amy/workshops/models.py", line 159, in save
    super().save(*args, **kwargs)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 971, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nhong/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

**Comment by wking** [comment]
On Mon, May 11, 2015 at 08:14:02AM -0700, Neil Chue Hong wrote:
> Still getting the same issue…
> …
> (py3k)MBANCH:amy nhong$  git log -1 --oneline
> cc5a178 Merge branch 'gvwilson-itemizing-unpublished-workshops'
> …
> django.db.utils.IntegrityError: NOT NULL constraint failed: workshops_person.last_login

Did you run the migrations?  After d9fbe6b (Add important migration to
Django 1.8, 2015-04-06, #243) Person.last_login should be nullable.
Try:

  $ python3 manage.py migrate

**Comment by npch** [comment]
Thanks @wking - that fixes the issue for me.

Should that instruction be added to the README.md between step 3 and 4?

**Comment by wking** [comment]
On Mon, May 11, 2015 at 09:25:57AM -0700, Neil Chue Hong wrote:
> Should that instruction be added to the README.md between step 3 and 4?

Thats the step you need for upgrading your local system after pulling
new amy code.  You won't need it on a fresh install.  Maybe a separate
section in the README on upgrading?  I think we have some notes on the
mailing list with some suggestions.  For example, you'll want to run
‘pip install … -r requirements.txt’ if any of the requirements were
changed, and it doesn't hurt to run the pip install or migrate
commands if there were no requirement or migrations added.

**Comment by npch** [comment]
@wking I had to do this on a fresh install (both Mac OS X Yosemite and Ubuntu 14.04) to make it work.

However I think that the discussion on this thread and the changes in #270 resolve this issue, so I'm closing it. Many thanks for your help!
